server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

scheduling:
  articles:
    rate: 3600000

springdoc:
  swagger-ui:
    path: /api/docs
  group-configs:
    - group: v1
      paths-to-match: /api/v1/**
